version: "3.4"

networks:
  main:
    driver: bridge

services:
  proxy:
    image: staticfloat/nginx-certbot
    container_name: proxy
    # restart: unless-stopped
    ports:
      - 80:80/tcp
      - 443:443/tcp
    environment:
      CERTBOT_EMAIL: philipp.sapronov@gmail.com
    networks:
      - main
    volumes:
      - ./proxy/conf.d:/etc/nginx/user.conf.d:ro
      - ./proxy/snippets:/etc/nginx/snippets:ro
      - letsencrypt:/etc/letsencrypt

  api:
    build:
      context: ./api
    container_name: api
    restart: unless-stopped
    env_file:
      - ./.env
    command: "yarn start"
    networks:
      - main

  frontend:
    build:
      context: ./next
      target: prod
      args:
        - NODE_ENV=${NODE_ENV}
    container_name: frontend
    restart: unless-stopped
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - main

volumes:
  letsencrypt:
